[server]
headless = true
port = 10000
# Se serve CORS libero, disattiva XSRF (Render non usa domini multipli, va bene così):
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#ffcc00"
